### ISSUE TITLE
Check the operation of the estimation code using 6 cells.

### ISSUE THREAD

**Issue by Kenkentake** [Kenkentake/optimizePara#12]
## Summary
Check the operation of the estimation code using 6 cells.

## Goal
Verify that the inferred code runs to the end using 6 cells.

## Todo
- [ ] prepare files for 6 cells
  - [ ] conMat.txt
  - [ ] conMat.tx
  - [ ] swc files
  - [ ] ist/neuronlist.txt
- [ ] run on Fugaku

## Deadline
xx/xx

## Parent issue
None

## References
None

## Notes
None

**Comment by Kenkentake** [comment]
6細胞用のファイルの作成完了

**Comment by Kenkentake** [comment]
6細胞でジョブを投げた結果
- CellSwc2.hoc内の`for(i=0; i<SectionNum; i=i+1){....}`のループが時間を要する（10306イテレーション）
  - 見た感じ、ジョブの出力は数秒に1回まとめて出力ファイルにダンプされる

**Comment by Kenkentake** [comment]
わかったこと
- update_weight()関数内のupdate_vec.x(index)でエラーが出ている（おそらくindex is out of range）
- importSynList.hocから読み込んでいるoutput_1.txtも入力ファイルの1つ
  - getSynList_LAL_VPC.pyを実行することで作成される接続パラメータを記述したファイル
  - clusterの引き継ぎディレクトリでは1~7396までのファイルを使用
疑問
- update_weight()関数内の`num_synapse_mat.x[i][j]`について
- output_1.txtファイルは6細胞で推定する時はどうすればよい？
  - おそらく新たに作成した方が良いのだろうが作り方要確認

**Comment by Kenkentake** [comment]
わかった事
- hocfile_forSBやsrc_forSB以外のディレクトリ内のファイルも使用しているみたい！（ディレクトリ名を変えた（src → _src）らエラーが出た）＿

**Comment by Kenkentake** [comment]
やったこと
- update_vecのサイズとindexの値の把握

わかった事
- index is out of rangeが発生し得る状況
  - update_vecサイズ：36
  - index：0~125

疑問
- 福田コードで記述されていた`num_of_pop_per_procs = receiveInfoAndPassData()` の必要性
  - 富岳上で記述するとエラー発生し、COするとエラー解消される。

**Comment by Kenkentake** [comment]
わかった事
- 引き継ぎ資料より、本来孫プロセスに渡されるべきパラメータ（1つの子プロセスが持つ遺伝子数・次元数・神経細胞回路に直した場合の接続数）が渡されていない。
  - make_neuro_spawn.c内のMPI_Comm_Spawn()関数の引数にspawn_argvが指定されていない
    - cluster内の過去のmake_neuro_spawn.cを見ても同様なので、networkSimulation.hocに上記3つのパラメータをベタ書きする必要がありそう

**Comment by Kenkentake** [comment]
現状整理
- receiveInfoAndPassData()内の[pc.broadcast(vec, root)](https://www.neuron.yale.edu/neuron/static/py_doc/modelspec/programmatic/network/parcon.html#ParallelContext.broadcast)での待機中にタイムオーバーでジョブ終了
- *.1.0（estimation_main.c, mplmcma.c）と*.1.0@1（make_neuro_spawn.c）の出力ファイルが生成されない
- receiveInfoAndPassData()をCOすると、pc.scatter_d(nullvec, rcv_pop_vec_weight, dim_cmaes * num_of_pop_per_procs, root)でエラー発生する
